# Generated by Django 3.2.2 on 2021-06-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('sponser', models.CharField(max_length=255)),
                ('speedkmh', models.CharField(max_length=255)),
                ('rpm', models.CharField(max_length=255)),
                ('gear', models.CharField(max_length=255)),
                ('gaspedal', models.CharField(max_length=255)),
                ('brakepedal', models.CharField(max_length=255)),
                ('clutchpedal', models.CharField(max_length=255)),
                ('steerangle', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('maxfuel', models.CharField(max_length=255)),
                ('aidfuelrate', models.CharField(max_length=255)),
                ('tyreradius', models.CharField(max_length=255)),
                ('tyrewear', models.CharField(max_length=255)),
                ('aidtyrerate', models.CharField(max_length=255)),
                ('aidstability', models.CharField(max_length=255)),
                ('aidautoclutch', models.CharField(max_length=255)),
                ('aidautoblip', models.CharField(max_length=255)),
                ('hasdrs', models.CharField(max_length=255)),
                ('hasers', models.CharField(max_length=255)),
                ('haskers', models.CharField(max_length=255)),
                ('accg', models.CharField(max_length=255)),
                ('wheelslip', models.CharField(max_length=255)),
                ('wheelload', models.CharField(max_length=255)),
                ('wheelpressure', models.CharField(max_length=255)),
                ('tyredirtyleve', models.CharField(max_length=255)),
                ('tyreinnertemperature', models.CharField(max_length=255)),
                ('tyremiddletemperature', models.CharField(max_length=255)),
                ('tyreoutertemperature', models.CharField(max_length=255)),
                ('tyrecoretemperature', models.CharField(max_length=255)),
                ('camberrad', models.CharField(max_length=255)),
                ('suspensiontravel', models.CharField(max_length=255)),
                ('damage', models.CharField(max_length=255)),
                ('turboboost', models.CharField(max_length=255)),
                ('finalff', models.CharField(max_length=255)),
                ('braketemperature', models.CharField(max_length=255)),
                ('aicontroll', models.CharField(max_length=255)),
                ('tyrecompound', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=255)),
                ('trackconfiguration', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currenttime', models.CharField(max_length=255)),
                ('besttime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splinelength', models.CharField(max_length=255)),
                ('sectorcount', models.CharField(max_length=255)),
                ('airdensity', models.CharField(max_length=255)),
                ('airtemperature', models.CharField(max_length=255)),
                ('roadtemperature', models.CharField(max_length=255)),
                ('windspeed', models.CharField(max_length=255)),
                ('winddirection', models.CharField(max_length=255)),
                ('surfacegrip', models.CharField(max_length=255)),
                ('sessionid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo')),
            ],
        ),
    ]
