# Generated by Django 3.2.2 on 2021-06-10 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speedkmh', models.CharField(max_length=255)),
                ('rpm', models.CharField(max_length=255)),
                ('gear', models.CharField(max_length=255)),
                ('gaspedal', models.CharField(max_length=255)),
                ('brakepedal', models.CharField(max_length=255)),
                ('clutchpedal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorcount', models.CharField(max_length=255)),
                ('airdensity', models.CharField(max_length=255)),
                ('airtemperature', models.CharField(max_length=255)),
                ('roadtemperature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.CharField(max_length=255)),
                ('trackconfiguration', models.CharField(max_length=255)),
                ('userid', models.ManyToManyField(related_name='UserHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
