# Generated by Django 3.2.2 on 2021-09-04 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=255)),
                ('trackconfiguration', models.CharField(max_length=255, null=True)),
                ('record', models.ManyToManyField(related_name='record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splinelength', models.CharField(max_length=255)),
                ('sectorcount', models.CharField(max_length=255)),
                ('airdensity', models.CharField(max_length=255)),
                ('airtemperature', models.CharField(max_length=255)),
                ('roadtemperature', models.CharField(max_length=255)),
                ('windspeed', models.CharField(max_length=255)),
                ('winddirection', models.CharField(max_length=255)),
                ('surfacegrip', models.CharField(max_length=255)),
                ('sessionid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currenttime', models.CharField(max_length=255)),
                ('besttime', models.CharField(max_length=255)),
                ('sessionid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('sponser', models.CharField(max_length=255)),
                ('speedkmh', models.CharField(max_length=255)),
                ('rpm', models.CharField(max_length=255)),
                ('gear', models.CharField(max_length=255)),
                ('gaspedal', models.CharField(max_length=255)),
                ('brakepedal', models.CharField(max_length=255)),
                ('clutchpedal', models.CharField(max_length=255)),
                ('steerangle', models.CharField(max_length=255)),
                ('tyrecompound', models.CharField(max_length=255)),
                ('sessionid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo')),
            ],
        ),
    ]
