# Generated by Django 3.2.2 on 2021-06-10 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datahandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='userid',
            field=models.ManyToManyField(related_name='record', to=settings.AUTH_USER_MODEL),
        ),
    ]
