# Generated by Django 3.2.2 on 2021-06-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0002_alter_sessioninfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='trackinfo',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
    ]
