# Generated by Django 3.2.2 on 2021-06-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0003_auto_20210610_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninfo',
            old_name='rack',
            new_name='track',
        ),
    ]
