# Generated by Django 3.2.2 on 2021-06-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0003_timeinfo_sessionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='tyredirtyleve',
            new_name='tyredirtylevel',
        ),
    ]
