# Generated by Django 3.2.2 on 2021-06-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0004_rename_tyredirtyleve_carinfo_tyredirtylevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='accg',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='braketemperature',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='camberrad',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='suspensiontravel',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='tyrecoretemperature',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='tyredirtylevel',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='tyreinnertemperature',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='tyremiddletemperature',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='tyreoutertemperature',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='tyreradius',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='tyrewear',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='wheelload',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='wheelpressure',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='wheelslip',
        ),
        migrations.CreateModel(
            name='CarWheelSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarWheelPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarWheelLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarTyreWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarTyreRadius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarTyreOuterTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarTyreMiddleTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarTyreInnerTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarTyreDirtyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarTyreCoreTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarSuspensionTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.CharField(max_length=255)),
                ('section2', models.CharField(max_length=255)),
                ('section3', models.CharField(max_length=255)),
                ('section4', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarCamberRAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarBrakeTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrefl', models.CharField(max_length=255)),
                ('tyrefr', models.CharField(max_length=255)),
                ('tyrerl', models.CharField(max_length=255)),
                ('tyrerr', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarAccG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('z', models.CharField(max_length=255)),
                ('carid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.carinfo')),
            ],
        ),
    ]
