# Generated by Django 3.2.2 on 2021-06-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0004_rename_rack_sessioninfo_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninfo',
            old_name='userid',
            new_name='record_id',
        ),
    ]
