# Generated by Django 3.2.2 on 2021-06-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0005_rename_userid_sessioninfo_record_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninfo',
            old_name='record_id',
            new_name='record',
        ),
    ]
