# Generated by Django 3.2.2 on 2021-06-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0005_auto_20210621_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caraccg',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='carbraketemperature',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='carcamberrad',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cardamage',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='carsuspensiontravel',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cartyrecoretemperature',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cartyredirtylevel',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cartyreinnertemperature',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cartyremiddletemperature',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cartyreoutertemperature',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cartyreradius',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='cartyrewear',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='carwheelload',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='carwheelpressure',
            name='carid',
        ),
        migrations.RemoveField(
            model_name='carwheelslip',
            name='carid',
        ),
        migrations.AddField(
            model_name='caraccg',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='carbraketemperature',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='carcamberrad',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cardamage',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='carsuspensiontravel',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cartyrecoretemperature',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cartyredirtylevel',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cartyreinnertemperature',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cartyremiddletemperature',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cartyreoutertemperature',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cartyreradius',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='cartyrewear',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='carwheelload',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='carwheelpressure',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
        migrations.AddField(
            model_name='carwheelslip',
            name='sessionid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datahandler.sessioninfo'),
        ),
    ]
