# Generated by Django 3.2.2 on 2021-06-15 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datahandler', '0007_remove_sessioninfo_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='record',
            field=models.ManyToManyField(related_name='record', to=settings.AUTH_USER_MODEL),
        ),
    ]
